# platform :ios, '8.0'

target 'Native_Demo' do

pod 'React', :path => '../node_modules/react-native',:subspecs => [

'Core',

'DevSupport', #如果RN版本>= 0.43，则需要加入此行才能开启开发者菜单

'RCTText',

'RCTNetwork',

'RCTWebSocket',

‘BatchedBridge’#这个模块是用于调试功能的

#在这里继续添加你所需要的模块

]
#如果你的RN版本>= 0.42.0，则加入下面这行

pod“yoga", :path=> "../node_modules/react-native/ReactCommon/yoga"


end
